import Foundation
import Rikka
import SwiftSoup

#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif

public struct CAS {
  internal static let COOKIE = "lemonldap"
  internal static let HOST = "https://cas.unilim.fr"
  internal static let PERSIST_COOKIE = "llngconnection"

  public enum Error: Swift.Error {
    case noCasToken
    case badPersistence
  }

  /// Your `lemonldap` session cookie, it is used to perform requests.
  public let cookie: String

  /// A persistence cookie.
  ///
  /// You can provide this to the `restore` method to
  /// re-authenticate without needing to manually solve 2FA.
  public let connection: String

  /// TOTP key generated by the persistence cookie.
  /// Also needed to re-authenticate without manually solving 2FA.
  public let key: String

  public init(cookie: String, connection: String, key: String) {
    self.cookie = cookie
    self.connection = connection
    self.key = key
  }

  /// Try to create a new session with the CAS by trying to obtain
  /// the authentication form and submit it.
  ///
  /// Once created, you'll be given a `PendingAuth`
  /// instance to continue the authentication process.
  public static func initialize(username: String, password: String) async throws -> PendingAuth {
    let token = try await getInitialTokenCSRF()

    let body = [
      "password": password,
      "stayconnected": "1",
      "token": token,
      "user": username,
    ]

    let request = try HttpRequest.Builder(HOST)
      .setMethod(.post)
      .setFormUrlEncodedBody(body)
      .build()

    let response = try await send(request)
    let document = try response.toHTML()

    // Let's delegate everything to PendingAuth.
    return try PendingAuth(document)
  }

  public static func restore(
    username: String, password: String,
    llngconnection: String, key: String
  ) async throws -> CAS {
    var body = [
      "password": password,
      "token": try await getInitialTokenCSRF(),
      "user": username,
    ]

    var request = try HttpRequest.Builder(HOST)
      .setMethod(.post)
      .setFormUrlEncodedBody(body)
      .setCookie(PERSIST_COOKIE, llngconnection)
      .build()

    var response = try await send(request)

    let document = try response.toHTML()
    guard let token = extractTokenCSRF(document) else {
      throw Error.noCasToken
    }

    body = [
      "fg": "TOTP_" + generate(key),
      "token": token,
      "usetotp": "1",
    ]

    request = try HttpRequest.Builder(HOST + "/checkbrowser")
      .setRedirection(.manual)
      .setMethod(.post)
      .setFormUrlEncodedBody(body)
      .setCookie(PERSIST_COOKIE, llngconnection)
      .build()

    response = try await send(request)

    let cookies = response.headers.getSetCookie()
    guard var lemonldap = cookies.first(where: { $0.hasPrefix(CAS.COOKIE + "=") })
    else { throw Error.badPersistence }
    lemonldap = String(lemonldap.split(separator: ";")[0].split(separator: "=")[1])

    return CAS(
      cookie: lemonldap,
      connection: llngconnection,
      key: key
    )
  }

  /// Return a new CAS instance by using the provided `cookie`.
  /// This might be useful for temporary usage.
  ///
  /// `connection` and `key` will be empty strings,
  /// you won't be able to restore the session with this method.
  ///
  /// If you prefer to do a whole authentication process,
  /// you might want to use `initialize`.
  public static func temporary(cookie: String) -> Self {
    return Self(cookie: cookie, connection: "", key: "")
  }

  private static func extractTokenCSRF(_ document: Document) -> String? {
    do {
      let token = try document.select("input[name=token]").attr("value")
      return token.isEmpty ? nil : token
    } catch {
      return nil
    }
  }

  /// Tries to retrieve the CSRF token from the CAS login portal.
  ///
  /// It retries 5 times before failing: sometimes an information
  /// page is shown and we need to refresh the page to dismiss it.
  private static func getInitialTokenCSRF() async throws -> String {
    let maxRetries = 5

    for _ in 0..<maxRetries {
      let request = try HttpRequest.Builder(HOST).build()
      let response = try await send(request)

      let document = try response.toHTML()
      if let token = extractTokenCSRF(document) { return token }
    }

    throw Error.noCasToken
  }
}
